In [31]:
# Neel Patel 202201494

 ### <span style="color:red">**Enter your name and person number here:**</span>

 # Taylor Smith 202312345

### Execute the cell below before proceeding.

The code in this cell will download a couple files with Python scripts from the Internet. Make sure that you have a network connection before executing it.  

In [2]:
import requests
with open("hill_cipher_extra_credit.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzP").text)
with open("hill_cipher_extra_credit_samples.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzX").text)
from hill_cipher_extra_credit import *

# Extra credit Hill cipher


## Instructions

* This is an assignment cum project exercise, you are required to submit it.
* The correct solution will carry 5% of your garde.
* There is no partial credit on this assignment. Incomplete solutions (e.g. incorrect decoding of the cipher, printing the decoded message without any computations  etc.) will receive no credit.
* The whole assignment must be completed within this notebook. Computations done on paper or using some other program will not be graded.
* Once you complete this assignment, send me the file through email. The name of this notebook file is `hill_cipher.ipynb`. You can execute the command `pwd` in a code cell of this notebook to check where this file is located on your computer.
* The submission deadline is **June 25, 11:59 PM**.

**Note:** The functions `char2num()` and `num2char()` should be helpful with this exercise. `char2num()` converts capital letters into numbers:

In [3]:
char2num("ABCDEF")

[1, 2, 3, 4, 5, 6]

Conversely, `num2char()` converts a list of numbers into corresponding characters. It also displays a black block for each number on the list that does not correspond to any character:

In [4]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char(mylist)

  20   8   9  19   0   9  19   0   1   0  20   5  19  20 100  -1
   T   H   I   S   _   I   S   _   A   _   T   E   S   T   #   #



The function `num2char_text_only()` is similar, but it prints only characters, without the corresponding numbers:

In [5]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char_text_only(mylist)

'THIS_IS_A_TEST##'

----

### Extra Credit Exercise

In the next cell enter your DA-IICT roll number (digits only, no spaces, dashes etc.) assigning it to the variable `pnum`, and execute the cell. For example, if your DA-IICT roll number is 202312345, then the next cell should be `pnum = 202312345`

In [1]:
pnum = 202201494

Execute the next cell to produce a message encrypted with the Hill cipher cipher:

In [6]:
cipher = cipher_generator(pnum)
cipher

[143, 130, 88, 115, 47, 35, 158, 179, 119, 91, 106, 70, 7, 1, 1, 187, 65, 50, 
148, 21, 21, 125, 126, 84, 92, 21, 18, 203, 49, 40, 224, 132, 93, 141, 43, 34,
 52, 101, 65, 119, 55, 40, 77, 121, 79, 7, 1, 1, 191, 199, 133, 124, 17, 17]

The encryption key is a 3$\times$3 matrix, and the message starts with the word "CONFIDENTIAL". Decrypt the message.

In [7]:
partial_decryption = "CONFIDENTIAL"
partial_num_d = char2num(partial_decryption)
partial_num_d

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12]

In [8]:
v01 = Matrix(partial_num_d[:3])
v02 = Matrix(partial_num_d[3:6])
v03 = Matrix(partial_num_d[6:9])
v04 = Matrix(partial_num_d[9:12])
v01, v02, v03, v04

⎛⎡3 ⎤  ⎡6⎤  ⎡5 ⎤  ⎡9 ⎤⎞
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎜⎢15⎥, ⎢9⎥, ⎢14⎥, ⎢1 ⎥⎟
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎝⎣14⎦  ⎣4⎦  ⎣20⎦  ⎣12⎦⎠

In [17]:
import numpy as np


CM = np.array([[143, 130, 88], #CM = Cipher Matrix
              [115, 47, 35],
              [158, 179, 119]])

def transpose_matrix(A):
    return [[CM[j][i] for j in range(len(CM))] for i in range(len(CM[0]))]

transposed_matrix = transpose_matrix(CM)

for row in transposed_matrix:
    print(row)


CMT = np.linalg.inv(transposed_matrix) #CMT = Cipher Matrix after Transpose

print(CMT)

[143, 115, 158]
[130, 47, 179]
[88, 35, 119]
[[-0.38487973 -4.67067583  7.53665521]
 [ 0.16151203  1.78293242 -2.89633448]
 [ 0.2371134   2.92955326 -4.71305842]]


In [18]:
Conf = ([[3, 6, 5],
      [15, 9, 14],
      [14, 4, 20]])

DK = [[0, 0, 0], #DK = Decryption key
     [0, 0, 0],
     [0, 0, 0]]

for i in range(len(CM)):
    for j in range(len(CMT[0])):
        for k in range(len(B)):
            DK[i][j] += Conf[i][k] * CMT[k][j]

for row in DK:
    print(row)

[0.9999999999998865, 11.33333333333194, -18.333333333331087]
[-0.9999999999998699, -12.999999999998408, 20.999999999997442]
[-1.7763568394002505e-15, 0.3333333333333073, -0.33333333333328596]


In [20]:
FDK = [[elem % 27 for elem in row] for row in DK] #FDK = Final Decryption Key

print(FDK)

[[0.9999999999998865, 11.33333333333194, 8.666666666668913], [26.00000000000013, 14.000000000001592, 20.999999999997442], [27.0, 0.3333333333333073, 26.666666666666714]]


In [25]:
FDK = [[0.9999999999998865, 11.33333333333194, 8.666666666668913],
      [26.00000000000013, 14.000000000001592, 20.999999999997442],
      [27.0, 0.3333333333333073, 26.666666666666714]]

vectors = [
    np.array([[143], [130], [88]]),
    np.array([[115], [47], [35]]),
    np.array([[158], [179], [119]]),
    np.array([[91], [106], [70]]),
    np.array([[7], [1], [1]]),
    np.array([[187], [65], [50]]),
    np.array([[148], [21], [21]]),
    np.array([[125], [126], [84]]),
    np.array([[92], [21], [18]]),
    np.array([[203], [49], [40]]),
    np.array([[224], [132], [93]]),
    np.array([[141], [43], [34]]),
    np.array([[52], [101], [65]]),
    np.array([[119], [55], [40]]),
    np.array([[77], [121], [79]]),
    np.array([[7], [1], [1]]),
    np.array([[191],[199],[133]]),
    np.array([[124],[17],[17]])
]

result = []

for i in vectors:
    FM = np.dot(FDK, i) #FM = final matrix
    result.append(FM)

all_result = np.vstack(result)

arr = np.array(all_result)
output_matrix = arr.reshape(1, -1)


print(output_matrix)

[[ 2379.  7386.  6251.   951.  4383.  4054.  3218.  9113.  7499.  1899.
   5320.  4359.    27.   217.   216.  1357.  6822.  6404.   568.  4583.
   4563.  2281.  6778.  5657.   486.  3064.  2971.  1105.  6804.  6564.
   2526.  9625.  8572.   923.  4982.  4728.  1760.  4131.  3171.  1089.
   4704.  4298.  2133.  5355.  4226.    27.   217.   216.  3599. 10545.
   8770.   464.  3819.  3807.]]


In [28]:
Matrix = [2379,  7386,  6251,   951,  4383,  4054,  3218,  9113,  7499,  1899,
   5320,  4359,    27,   217,   216,  1357,  6822,  6404,   568,  4583,
   4563,  2281,  6778,  5657,   486,  3064,  2971,  1105,  6804,  6564,
   2526,  9625,  8572,   923,  4982,  4728,  1760,  4131,  3171,  1089,
   4704,  4298,  2133,  5355,  4226,    27,   217,   216,  3599, 10545,
   8770,   464,  3819,  3807]

In [29]:
final_Sequence = [elem % 27 for elem in Matrix]

print(final_Sequence)

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12, 0, 1, 0, 7, 18, 5, 1, 20, 0, 13, 1, 14, 0, 13, 1, 25, 0, 3, 15, 13, 13, 5, 14, 3, 5, 0, 12, 9, 6, 5, 0, 9, 14, 0, 1, 0, 8, 15, 22, 5, 12, 0]


In [30]:
num2char(final_Sequence)

   3  15  14   6   9   4   5  14  20   9   1  12   0   1   0   7  18   5   1  20
   C   O   N   F   I   D   E   N   T   I   A   L   _   A   _   G   R   E   A   T

   0  13   1  14   0  13   1  25   0   3  15  13  13   5  14   3   5   0  12   9
   _   M   A   N   _   M   A   Y   _   C   O   M   M   E   N   C   E   _   L   I

   6   5   0   9  14   0   1   0   8  15  22   5  12   0
   F   E   _   I   N   _   A   _   H   O   V   E   L   _



A GREAT MAN MAY COMMENCE LIFE IN A HOVEL